[project]
name = "mm"
version = "0.0.0"
description = "Matrix multiplication in C"
requires-python = ">=3.10"

[build-system]
requires = ["scikit-build-core>=0.10"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
wheel.py-api = "cp310"
build.verbose = true